apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: kompose convert -f docker-product.yml
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose convert -f docker-product.yml","kompose.version":"1.16.0 (0c01309)"},"creationTimestamp":null,"labels":{"io.kompose.service":"database"},"name":"database","namespace":"default"},"spec":{"replicas":1,"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"io.kompose.service":"database"}},"spec":{"containers":[{"env":[{"name":"MYSQL_ROOT_PASSWORD","value":"3amFNS5kqs"}],"image":"mysql:5.6","name":"database","resources":{},"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"pvc"}]}],"restartPolicy":"Always","volumes":[{"name":"pvc","persistentVolumeClaim":{"claimName":"database-data"}}]}}},"status":{}}
  creationTimestamp: "2020-06-06T09:11:26Z"
  generation: 1
  labels:
    io.kompose.service: database
  name: database
  namespace: default
  resourceVersion: "3876"
  selfLink: /apis/apps/v1/namespaces/default/deployments/database
  uid: b3736f48-a7d5-11ea-9d46-42010a8c00f2
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: 3amFNS5kqs
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        name: database
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: database-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-06T09:16:12Z"
    lastUpdateTime: "2020-06-06T09:16:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
